[package]
name = "garuda"
version = "0.1.0"
description = "An implementation of the Garuda SNARK"
keywords = ["zero-knowledge", "cryptography", "zkSNARK", "SNARK", "constraint-systems"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"


################################# Dependencies ################################

[dependencies]
ark-serialize = { version = "^0.5.0", default-features = false, features = [ "derive" ] }
ark-ff = { version = "^0.5.0", default-features = false }
ark-ec = { version = "^0.5.0", default-features = false }
ark-std = { version = "^0.5.0", default-features = false }
ark-poly = { version = "^0.5.0", default-features = false }
num-bigint = "0.4.4"
rayon = { version = "1.5.2", optional = true }
digest = { version = "^0.10.0" }
derivative = { version = "2", features = ["use_core"] }

hp-arithmetic = { package = "arithmetic", path = "../arithmetic", default-features = false }
hp-transcript = { package = "transcript", path = "../transcript", default-features = false }
hp-subroutines = { package = "subroutines", path = "../subroutines" }

ark-poly-commit = { path = "../poly-commit" , default-features = false}
ark-relations = { path = "../relations" , default-features = false}
ark-bls12-381 = { version = "^0.5.0", default-features = false, features = [ "curve" ] }
ark-gr1cs-std = { path = "../ark-gr1cs-std", default-features = false }
rescue-gr1cs-custom = { path = "../rescue_gr1cs_custom", default-features = false }


[[bench]]
name = "garuda-benches"
path = "benches/bench.rs"
harness = false


[features]
bench = ["parallel"]
default = ["parallel"]
parallel = ["ark-ff/parallel", "ark-poly/parallel", "ark-ec/parallel", "ark-std/parallel", "rayon",]