[workspace]
members = [ "shared-utils","garuda", "garuda-bench", "pari", "pari-bench"]

resolver = "2"  # Recommended for workspaces to avoid dependency resolution issues



[workspace.dependencies]
ark-serialize = { version = "^0.5.0", default-features = false, features = [ "derive" ] }
ark-ff = { version = "^0.5.0", default-features = false }
ark-ec = { version = "^0.5.0", default-features = false }
ark-std = { version = "^0.5.0", default-features = false }
ark-poly = { version = "^0.5.0", default-features = false }
ark-r1cs-std = { path = "../r1cs-std", default-features = false }
ark-groth16 = { path = "../groth16", default-features = false }
ark-relations = {  path = "../snark/relations", default-features = true }
merlin = { version = "3.0.0", default-features = false }
displaydoc = { version = "0.2.3", default-features = false }
tracing = { version = "0.1", default-features = false, features = [ "attributes" ] }
rayon = { version = "1.5.2" }
lazy_static = "1.4"
csv = "1.2"
num-bigint = "0.4.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ark-crypto-primitives = { path = "../crypto-primitives/crypto-primitives", default-features = false, features = [
    "snark",
    "crh",
] }
ark-bls12-381 = { version = "^0.5.0", default-features = false, features = [
    "curve",
] }

ark-bn254 = { version = "^0.5.0", default-features = false, features = [
    "curve",
] }
