[package]
name = "garuda-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
garuda = { path = "../garuda" }
shared-utils = { path = "../shared-utils" }
ark-serialize = { workspace = true }
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-std = { workspace = true }
ark-poly = { workspace = true }
ark-crypto-primitives = { workspace = true }
ark-r1cs-std = { workspace = true, features = [ "std" ] }
ark-relations = { workspace = true }
merlin = { workspace = true }
displaydoc = { workspace = true }
tracing = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
num-bigint = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-spartan = { git = "https://github.com/alireza-shirzad/spartan.git", default-features = false }


# These are for the hyperplonk benches
hp-hyperplonk = { package = "hyperplonk", git = "https://github.com/alireza-shirzad/hyperplonk" }
hp-subroutines = { package = "subroutines", git = "https://github.com/alireza-shirzad/hyperplonk" }
ark-bls12-381-v4 = { package = "ark-bls12-381", version = "0.4.0", default-features = false, features = [
    "curve",
] }
ark-ff-v4 = { package = "ark-ff", version = "0.4.0" }
ark-ec-v4 = { package = "ark-ec", version = "0.4.0" }
ark-crypto-primitives-v4 = { package = "ark-crypto-primitives", version = "0.4.0", features = [
    "snark",
    "crh",
] }
ark-serialize-v4 = { package = "ark-serialize", version = "0.4.0" }
rand = "0.8.5"
hashbrown = { workspace = true }


[[bench]]
name = "rescue-garuda-gr1cs"
path = "benches/rescue-garuda-gr1cs.rs"
harness = false


[[bench]]
name = "rescue-garuda-r1cs"
path = "benches/rescue-garuda-r1cs.rs"
harness = false


[[bench]]
name = "rescue-spartan-r1cs"
path = "benches/rescue-spartan-r1cs.rs"
harness = false

[[bench]]
name = "rescue-spartan-ccs"
path = "benches/rescue-spartan-ccs.rs"
harness = false


[[bench]]
name = "rescue-hyperplonk"
path = "benches/rescue-hyperplonk.rs"
harness = false


[[bench]]
name = "rescue-gr1cs-synthesis"
path = "benches/rescue-gr1cs-synthesis.rs"
harness = false

[features]
default = ["std", "parallel"]
std = [
    "garuda/std",
    "ark-ff/std",
    "ark-poly/std",
    "ark-relations/std",
    "ark-std/std",
    "ark-serialize/std",
]
print-trace = ["ark-std/print-trace", "ark-spartan/profile"]
parallel = [
    "std",
    "ark-ec/parallel",
    "ark-ff/parallel",
    "garuda/parallel",
    "ark-poly/parallel",
    "ark-std/parallel",
    "hp-hyperplonk/parallel",
    "hp-subroutines/parallel",
    "ark-spartan/multicore",
    "rayon",
]

r1cs = ["ark-crypto-primitives/r1cs"]
gr1cs = ["ark-crypto-primitives/gr1cs"]
