[package]
name = "garuda-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
garuda = { path = "../garuda" }
shared-utils = { path = "../shared-utils" }
ark-serialize = { workspace = true }
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-std = { workspace = true }
ark-poly = { workspace = true }
ark-crypto-primitives = { workspace = true}
ark-r1cs-std = { workspace = true }
ark-relations = { workspace = true }
merlin = { workspace = true }
displaydoc = { workspace = true }
tracing = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
num-bigint = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-bls12-377 = { workspace = true }
spartan = "0.9.0"


# These are for the hyperplonk benches
hp-hyperplonk = { package = "hyperplonk", git = "https://github.com/EspressoSystems/hyperplonk.git" }
hp-subroutines = { package = "subroutines", git = "https://github.com/EspressoSystems/hyperplonk.git" }
ark-bls12-381-v4 = { package = "ark-bls12-381", version = "0.4.0", default-features = false, features = [
    "curve",
] }
ark-ec-v4 = { package = "ark-ec", version = "0.4.0" }
ark-serialize-v4 = { package = "ark-serialize", version = "0.4.0" }
curve25519-dalek = { version = "4.1.1", features = [
    "serde",
    "alloc",
    "rand_core",
], default-features = false }
rand = "0.8.5"


[[bench]]
name = "rescue-garuda-gr1cs"
path = "./rescue-garuda-gr1cs.rs"
harness = false


[[bench]]
name = "rescue-garuda-r1cs"
path = "./rescue-garuda-r1cs.rs"
harness = false


[[bench]]
name = "rescue-spartan-r1cs"
path = "./rescue-spartan-r1cs.rs"
harness = false

[[bench]]
name = "rescue-hyperplonk"
path = "./rescue-hyperplonk.rs"
harness = false


[features]
default = ["std", "parallel"]
std = [
    "garuda/std",
    "ark-ff/std",
    "ark-poly/std",
    "ark-relations/std",
    "ark-std/std",
    "ark-serialize/std",
]
print-trace = ["ark-std/print-trace"]
parallel = [
    "std",
    "ark-ff/parallel",
    "garuda/parallel",
    "ark-poly/parallel",
    "ark-std/parallel",
    "rayon",
]

r1cs = [
    "ark-crypto-primitives/r1cs",
]
gr1cs = [
    "ark-crypto-primitives/gr1cs",
]

# Plots for the paper:
# Remove constraints plot
# Prover time (NUM_THREAD = 1,4) for Garuda GR1CS, Garuda R1CS, Spartan CCS, Spartan R1CS, Hyperplonk
# VErifier time for Garuda GR1CS, Garuda R1CS, Spartan CCS, Spartan R1CS, Hyperplonk
# Proof size for Garuda GR1CS, Garuda R1CS, Spartan CCS, Spartan R1CS, Hyperplonk
# PK and VK size for Garuda GR1CS, Garuda R1CS, Spartan CCS, Spartan R1CS, Hyperplonk